var Constant = require('../Constant/constant');
var fs       = require('fs');

function Upload(UserModel, UploadModel){

	function retrieveUserID(userName){
		
		var query = UserModel.find({userName : userName}, '_id');
		return query.exec();
	}

	function getExtension(fileName){
		var ext;

		//return the extension of the image, 
		//if no extension specified, jpg will be used instead
		return (ext = fileName.split('.').pop() ? ext : 'jpg');
	}
	/*
		return the user id if it is exist in the database
	*/
	function retrieveUserIDSuccessCallBack(doc){
		
		if(doc){

			switch(doc.length){
				
				case Constant.constant.NUMBER.NO_USER_EXIST : 
					return false;
				break;
				
				case Constant.constant.NUMBER.USER_ALREADY_EXIST:
					return doc[0]._id;	
				break;
				
				default:
					throw(Constant.constant.DATABASE.ERROR.USER_NAME_DATABASE_ERROR.EXIST_MORE_THAN_ONE_USER_NAME);
					return false;
				
				break;
			}
		}
		else
			return false;
	}

	function serverErrorCallBack(err){

		if(err){
			throw(err);
		}

		return {
				code : Constant.constant.ERROR.SERVER_ERROR.code, 
				message : Constant.constant.ERROR.SERVER_ERROR.message
			};
	}

	function storeImageErrorCallBack(){

		return {
				code : Constant.constant.ERROR.IMAGE_UPLOAD_ERROR.code, 
				message : Constant.constant.ERROR.IMAGE_UPLOAD_ERROR.message
			};
	}

	/*
		write image file into server
	*/
	function writeImage(newPath, fileName, ext, res, data){

		fs.writeFile(newPath + '/' + fileName + '.' + ext, data, function(err){
					
			if(err){
				throw(err);
				res.json(storeImageErrorCallBack());
			}
			else{
				res.json({
							code    : Constant.constant.STATUS.SUCCESS.UPLOAD_SUCCESS.code,
						  	message : Constant.constant.STATUS.SUCCESS.UPLOAD_SUCCESS.message 
						  });
			}
		})
	}

	function storeImageInFD(res, userID, path, fileName, ext){

		fs.readFile(path, function(err, data){
			
			var newPath    = __dirname + "/../../uploads/" + userID + '/';
			var uploadPath = __dirname + "/../../uploads/"; 

			if(!err){

				fs.stat(uploadPath, function(error, stats){

					//if folder uploads no exist
					if(error){

						//create upload folder
						fs.mkdir(uploadPath, function(error){

							if(error){

								//throw error if creating got problem
								throw(error);
								res.json(serverErrorCallBack());
							}
							else{

								//check folder user exist
								fs.stat(newPath, function(error, stats){

									//folder user not exist
									if(error){

										//create folder for user
										fs.mkdir(newPath, function(error){

											//if can not create folder
											if(error){

												//throw error if creating got problem
												throw(error);
												res.json(serverErrorCallBack());
											}
											else{

												//create file
												writeImage(newPath, fileName, ext, res, data);
											}
										})
									}
									else{

										//folder user exist
										//create file
										writeImage(newPath, fileName, ext, res, data);
									}			
								})
							}
						})
					}
					else{

						//folder already exist
						//check folder user exist
						fs.stat(newPath, function(error, stats){

							//folder user not exist
							if(error){

								//create folder for user
								fs.mkdir(newPath, function(error){

									//if can not create folder
									if(error){

										//throw error if creating got problem
										throw(error);
										res.json(serverErrorCallBack());
									}
									else{

										//create file
										writeImage(newPath, fileName, ext, res, data);
									}
								})
							}
							else{

								//folder user exist
								//create file
								writeImage(newPath, fileName, ext, res, data);
							}			
						})
					}
				})
			}
			else{

				throw(err);
				res.json(storeImageErrorCallBack());
			}
		})
	}

	function insertImageInDB(res, userID, files, data){

		var ext   = (files.file.originalFileName ? getExtension(files.file.originalFileName) : getExtension(''));
		var title, choice;

		//the data needed is : title, select, extension, userID
		if(data.title && data.select && files){
			
			title  = data.title;
			choice = data.select;

			//push the data of image into the database
			UploadModel.findOneAndUpdate({userID : userID}, {$push : {image : {title : title, choice : choice, ext : ext}}}, {upsert : true}, function(error, doc){

				if(!error && doc){

					//get the last data from the doc call back to get the id of the image
					//the id is a ramdom string generated by the database
					var fileName = doc.image[doc.image.length - 1]._id || 'defaultname';
					var path     = files.file.path || '';
					
					//store that image in server 
					storeImageInFD(res, userID, path, fileName, ext);
				}
				else{
					res.json(storeImageErrorCallBack(error));
				}
			})
		}
		else{
			res.json({
					  code    : Constant.constant.STATUS.ERROR.USER_CREDENTIAL_WRONG_FORMAT.code,
					  message : Constant.constant.STATUS.ERROR.USER_CREDENTIAL_WRONG_FORMAT.message
					})
		} 
	}

	function insertQuestionInDB(res, userID, title, answers, select){

		UploadModel.findOneAndUpdate({userID : userID}, {$push : {question : {title : title, answers : answers, select : select}}}, {upsert : true}, function(error, doc){

			if(!error && doc){

				res.json({
							code    : Constant.constant.STATUS.SUCCESS.UPLOAD_SUCCESS.code,
						  	message : Constant.constant.STATUS.SUCCESS.UPLOAD_SUCCESS.message 
						  });
			}
			else{
				res.json(serverErrorCallBack(error));
			}
		})
	}

	this.uploadImage = function(req, res){

		var userName = req.session.userName;
		var files    = req.files;
		var data     = req.body;

		retrieveUserID(userName).

			then(function(doc){
				
				var id;
				
				if(!(id = retrieveUserIDSuccessCallBack(doc))){
					
					res.json(serverErrorCallBack());
				}
				else{

					insertImageInDB(res, id, files, data);
				}

			}, function(err){

				res.json(serverErrorCallBack(err));
			})
	}

	this.uploadQuestion = function(req, res){

		var data 	 = req.body;
		var userName = req.session.userName;

		retrieveUserID(userName).

			then(function(doc){
				
				var id;
				
				if(!(id = retrieveUserIDSuccessCallBack(doc))){
					
					res.json(serverErrorCallBack());
				}
				else{
					
					if(data.title && data.answers && data.select){
						insertQuestionInDB(res, id, data.title, data.answers, data.select);
					}
					else
						res.json({
								  code    : Constant.constant.STATUS.ERROR.USER_CREDENTIAL_WRONG_FORMAT.code,
								  message : Constant.constant.STATUS.ERROR.USER_CREDENTIAL_WRONG_FORMAT.message
								})
				}

			}, function(err){

				res.json(serverErrorCallBack(err));
			})		
	}
}

exports.upload = Upload;